remote_theme: "mmistakes/minimal-mistakes@4.17.2"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache  #required by minimal-mistakes
  - jekyll-paginate
minimal_mistakes_skin: "dark"

search                    : true
search_full_content       : true
#  Lunr search only indexes collection documents e.g. posts or any custom collections you have. It does not currently index site.pages.';
search_provider: google
# google:
  # search_engine_id: 014994008257058938644:cb7qedcky7m


# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "UA-116749276-1"
#     anonymize_ip: true

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      toc: true
      comments: true
      share: true
  - scope:
      path: "zk-coach"
    values:
      sidebar:
        nav: "zk-coach"

comments:
  provider: "disqus"
  disqus:
    shortname: "zk-coach"
# disqus admin is 